name: 'Slack Message'
description: 'send message or upload file in slack '
inputs:
  SLACK_MESSAGE:  # id of input
    description: 'message to send'
    required: true
    default: 'hello'
  SLACK_CHANNEL:
    description: 'slack channel'
    required: true
  SLACK_TOKEN:
    description: 'slack app token'
    required: true
  SLACK_SIGNING_SECRET:
    description: 'slack app signing secret '
    required: true
  FILE_PATH:
    description: 'path of file to upload'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
